### ISSUE TITLE
JSX elements within JS-blocks inside of JSX-blocks need to be wrapped in parentheses

### ISSUE THREAD

**Issue by peitalin** [peitalin/vim-jsx-typescript#1]
E.g for a code block like this:
```
render() {
  return (
    <div>
        { 
            this.showIfTrue &&
            <Modal/>
        }
    <div>
  )
}
```
The last `}` will not be correctly highlighted.

You'll need to wrap the `<Modal/>` element inside the JS-block (inside the JSX-block) in parentheses:
```
render() {
  return (
    <div>
        { 
            this.showIfTrue &&
            (<Modal/>)
        }
    <div>
  )
}
```

Alternatively, I've been wrapping the entire block in parentheses for consistency:
```
render() {
  return (
    <div>
        {( 
            this.showIfTrue &&
            <Modal/>
        )}
    <div>
  )
}
```

**Comment by setthase** [comment]
Any plans to fix this issue?

The workaround will not work for projects that use `prettier` for they code formatting.

**Comment by peitalin** [comment]
Should be fixed now. 
![image](https://user-images.githubusercontent.com/4037878/51420963-6ce53e80-1be3-11e9-9274-08467a0b8b32.png)

**Comment by peitalin** [comment]
Should also work for react fragments syntax as well now.
![image](https://user-images.githubusercontent.com/4037878/51423241-c0b64e80-1c08-11e9-81c9-c2a225cf4c70.png)
