### ISSUE TITLE
Highlighting issue: related to genrics in method calls and interfaces

### ISSUE THREAD

**Issue by NullVoxPopuli** [peitalin/vim-jsx-typescript#11]
![image](https://user-images.githubusercontent.com/199018/56519692-b6aa3180-6510-11e9-84c5-177d0527d952.png)
Here is the file: https://github.com/sillsdev/appbuilder-portal/blob/develop/source/SIL.AppBuilder.Portal.Frontend/src/ui/routes/projects/show/overview/products/index.tsx

Maybe this is a regex mishap? idk
can't tell if it's an issue with the generic param to `useOrbit` or with the `/` in the template string of `useLiveData`.

**Comment by NullVoxPopuli** [comment]
Looks like it's generics:
![image](https://user-images.githubusercontent.com/199018/56526376-312b7f00-651a-11e9-8954-d89b9e863fcf.png)

**Comment by peitalin** [comment]
Hi, thanks for the heads up. I'm having some difficulty reproducing what you see, although I can't see the rest of the 2nd screenshot. 
![image](https://user-images.githubusercontent.com/4037878/56807193-7381f280-6871-11e9-9988-f2ef640aba23.png)
![image](https://user-images.githubusercontent.com/4037878/56807560-919c2280-6872-11e9-9ef6-2b6c47f6156a.png)

Can you try it on a clean install of vim and see if it's still there?

**Comment by NullVoxPopuli** [comment]
hmm. interesting, yeah. I must have a conflicting highlighter or something. weird.

![image](https://user-images.githubusercontent.com/199018/56808146-ca021900-67fe-11e9-9f5b-252b88032bf6.png)
![image](https://user-images.githubusercontent.com/199018/56808178-d8503500-67fe-11e9-8de1-a563e48a1efe.png)

but now I can't replicate. there must be some difference between the two computers I've been using. hmm.

Investigation continues...

**Comment by NullVoxPopuli** [comment]
oh wait, new computer, didn't have this plugin installed. ok. cool. back to replicating.

**Comment by NullVoxPopuli** [comment]
![image](https://user-images.githubusercontent.com/199018/56808454-907ddd80-67ff-11e9-94d5-fb7daec78278.png)

**Comment by NullVoxPopuli** [comment]
with this one, I disabled two plugins:
" Plug 'maxmellon/vim-jsx-pretty'
" Plug 'mxw/vim-jsx'

![image](https://user-images.githubusercontent.com/199018/56808498-a7243480-67ff-11e9-9013-085c2446b57e.png)

the rest of the file looks fine

**Comment by NullVoxPopuli** [comment]
ah ha! this one is the issue: https://github.com/HerringtonDarkholme/yats.vim
removing that fixes everything. cool :+1:

**Comment by NullVoxPopuli** [comment]
@peitalin what theme are you using in those screenshots?

**Comment by peitalin** [comment]
@NullVoxPopuli I'm using "onedark" with a few edits:
```vim
Plug 'joshdick/onedark.vim'
...
...
""""""""""""" Color Schemes """"""""""""""""
set termguicolors
colorscheme onedark

highlight Normal guibg=#202328
highlight MatchParen guifg=#C678DD guibg=#504066
highlight LineNr    guifg=#151822
highlight CursorLineNr guifg=#56B6C2
highlight Error guifg=#f57373 guibg=#804040
highlight vimError guifg=#f57373 guibg=#804040

hi IndentGuidesEven guibg=#2a2e30 guifg=#24282a
hi IndentGuidesOdd guibg=#262a2c guifg=#24282a
hi Comment cterm=italic guifg=#4a5158
hi String guifg=#98C379 guibg=#2a2e34

" Yellows
hi Number guifg=#E5C07B
hi Special guifg=#E5C07B
hi Boolean guifg=#E5C07B
hi Type guifg=#F0A15F

" purple
hi CtrlPMatch guifg=#ba9ef7
hi Visual guibg=#364652
hi Keyword guifg=#ba9ef7
hi Function guifg=#5682A3

" light blue
hi tsxTagName guifg=#59ACE5
" dark blue
hi tsxCloseString guifg=#2974a1
hi tsxCloseTag guifg=#2974a1
hi tsxAttributeBraces guifg=#2974a1
hi tsxEqual guifg=#2974a1
" green
hi tsxAttrib guifg=#1BD1C1


" cyan
hi Constant guifg=#56B6C2
hi typescriptBraces guifg=#56B6C2
hi typescriptEndColons guifg=#56B6C2
hi typescriptRef guifg=#56B6C2
hi typescriptPropietaryMethods guifg=#56B6C2
hi typescriptEventListenerMethods guifg=#56B6C2
hi typescriptFunction guifg=#56B6C2
hi typescriptVars guifg=#56B6C2
hi typescriptParen guifg=#56B6C2
hi typescriptDotNotation guifg=#56B6C2
hi typescriptBracket guifg=#56B6C2
hi typescriptBlock guifg=#56B6C2
hi typescriptJFunctions guifg=#56B6C2
hi typescriptSFunctions guifg=#56B6C2
hi typescriptInterpolationDelimiter guifg=#56B6C2
hi typescriptExceptions guifg=#DDA671
hi typescriptIdentifier guifg=#65809D
hi typescriptStorageClass guifg=#65809D

" JSX Dark Blue and Neon Green highlights
hi xmlEndTag guifg=#2974a1
hi tsxCloseString guifg=#15608f
hi htmlTag guifg=#2974a1
hi htmlEndTag guifg=#2974a1
hi htmlTagName guifg=#59ACE5
hi tsxAttrib guifg=#1BD1C1

hi tsxTypeBraces guifg=#BDA7CC
hi tsxTypes guifg=#8D779C
hi tsxIfOperator guifg=#56B6C2
hi tsxElseOperator guifg=#56B6C2

" React keywords
hi ReactState guifg=#C176A7
hi ReactProps guifg=#D19A66
hi ApolloGraphQL guifg=#CB886B
hi Events ctermfg=204 guifg=#56B6C2
hi ReduxKeywords ctermfg=204 guifg=#C678DD
hi WebBrowser ctermfg=204 guifg=#56B6C2
hi ReactLifeCycleMethods ctermfg=204 guifg=#D19A66
```
