### ISSUE TITLE
How to make open tag and close tag have the same color?

### ISSUE THREAD

**Issue by michael-land** [peitalin/vim-jsx-typescript#12]
![image](https://user-images.githubusercontent.com/33362998/58002769-ec592080-7aa4-11e9-9563-bee5e179b51b.png)

In your first render method,  `<provider>` and` </Provider> `have different color.

**Comment by michael-land** [comment]
nvm. figured out.

**Comment by avilesj** [comment]
But why close the issue without explaining how?

**Comment by xiaoyu-tamu** [comment]
You can customize colors via variables.

**Comment by michael-land** [comment]
> But why close the issue without explaining how?

You can customize colors via variables.
