### ISSUE TITLE
Using generics in tsx modules parses as tsxTagName & tsxTagAttrib

### ISSUE THREAD

**Issue by joefiorini** [peitalin/vim-jsx-typescript#15]
When I have an arrow function that uses generics in a TSX file it parses the first generic argument (up to and including the "," after the argument) as `tsxTagName` and the second argument as `tsxAttrib`. I'm using the excellent `vim-HiLinkTrace` plugin to see the syntax highlighting trace.

![image](https://user-images.githubusercontent.com/3648/64550837-bebd0f00-d301-11e9-9de0-8671cfb0d112.png)

![image](https://user-images.githubusercontent.com/3648/64550825-b7960100-d301-11e9-9be9-18d2038487cb.png)

You can see that although the `type` def works fine, the generics in the arrow definition do not.

If I change it to a named function instead it seems like it gets parsed as plain text:

![image](https://user-images.githubusercontent.com/3648/64550940-faf06f80-d301-11e9-8cd3-5791a65f54ca.png)

I feel like in both cases this should parse as a `tsxType` or `tsxGenerics`, no?

I tried to fix it myself, but these regexes are a little beyond my reach at the moment. Any thoughts?

I created a simple repo to reproduce the issue: https://github.com/joefiorini/tsx-generics-syntax-repro

It uses vim-plugged to install the plugins. Can be run in NeoVim with `nvim -u init.vim`.

**Comment by peitalin** [comment]
Hi Joe,
Thanks for providing the repo, I've made some edits to include those generics that exist in those places (outside of tsxRegions). Let me know if it works.
![image](https://user-images.githubusercontent.com/4037878/64630373-53298d80-d438-11e9-9395-7b419be40711.png)

**Comment by joefiorini** [comment]
Sorry it took me so long to respond. I think it's a little better, but I still see some issues. I've updated my example repo to include a few more examples that seem to break for me. I'll also include a screenshot here

![image](https://user-images.githubusercontent.com/3648/65628268-1c5a8800-df9f-11e9-9d98-e6055129a173.png)

**Comment by peitalin** [comment]
Hi Joe,
Thanks for providing the new examples. Let's see if this latest commit helps solve the issue.
![Screen Shot 2019-09-27 at 12 03 56 pm](https://user-images.githubusercontent.com/4037878/65736889-01fbe800-e120-11e9-8de2-afc38d79614a.jpg)

We could also add syntax rules for say the `Props['type']` part and make it customizable as an additional feature in the future.
