### ISSUE TITLE
it is setting .jsx as typescript.tsx

### ISSUE THREAD

**Issue by ApolloTang** [peitalin/vim-jsx-typescript#16]
When I install this plugin it is setting .jsx as ft=typescript.tsx 
I wondering if this is intentional ? or a mistake

**Comment by peitalin** [comment]
Hi, This is intentional, the syntax highlighter should work for both javascript.jsx and typescript.tsx files.

**Comment by filipekiss** [comment]
Can you please consider another way of handling this instead of setting `javascript.jsx` files to `typescript.tsx`? I have configurations that should only be applied to typescript being applied to javascript and it's making it really difficult to manage things.
