### ISSUE TITLE
Issue with template string

### ISSUE THREAD

**Issue by conradob** [peitalin/vim-jsx-typescript#17]
When using template string it isn't working properly.

![image](https://user-images.githubusercontent.com/1469697/66470259-25f4ed00-ea81-11e9-9f27-935a2b1681f1.png)

**Comment by peitalin** [comment]
Thanks for letting me know, made an edit to fix.
Please let me know if the issue persists.

![image](https://user-images.githubusercontent.com/4037878/66475748-4bace100-ead7-11e9-8061-935ea31526d2.png)

**Comment by conradob** [comment]
Hi, thanks for your reply and support but the issue is not fixed.

These are the plugins I'm currently using
```
Plug 'pangloss/vim-javascript'
Plug 'HerringtonDarkholme/yats.vim'
Plug 'peitalin/vim-jsx-typescript'
```

![image](https://user-images.githubusercontent.com/1469697/66573702-04703000-eb6b-11e9-9d3c-f6c5c99bf215.png)

**Comment by peitalin** [comment]
I think someone ran into the same issue before,
might be a clash with the `yats` library.
See https://github.com/peitalin/vim-jsx-typescript/issues/11

**Comment by conradob** [comment]
yes, it's a conflict with `yats` plugin
just replaced `yats` with `leafgarland/typescript-vim` and it's looking good now

![image](https://user-images.githubusercontent.com/1469697/66574898-f6231380-eb6c-11e9-9d36-62d879e24692.png)

I'm happy with `leafgarland/typescript-vim` but just for curiosity, any plan to check this issue when using `yats`?

thanks for your support.
