### ISSUE TITLE
One-line JSX with embedded javascript seems to give problem

### ISSUE THREAD

**Issue by rnmp** [peitalin/vim-jsx-typescript#19]
![image](https://user-images.githubusercontent.com/22627/69500489-8fae4680-0ec9-11ea-9523-128f718b5972.png)

Note how the close tag doesn't match the open tag. Compare to this:

![image](https://user-images.githubusercontent.com/22627/69500498-a0f75300-0ec9-11ea-96ed-9e04752454a1.png)

Is this a bug or am I missing a special configuration?

**Comment by rnmp** [comment]
Btw I think it may be related to how `tsxJsBlocks` are defined, my gut tells me that everything after `}` gets interpreted as a javascript expression, hence the `<` colored as a lower than sign.

**Comment by peitalin** [comment]
Hi @rnmp thanks for submitting this bug, I've made a few fixes.

![image](https://user-images.githubusercontent.com/4037878/69516700-2f3d0900-0f9e-11ea-81f9-f46f9653ecc7.png)

Please check it out and let me know if you run into any issues.

**Comment by rnmp** [comment]
All fixed up! Thanks for getting to it so quickly! I actually just switched back to vim after years, and having proper TSX syntax coloring was one of my only minor concerns.
