### ISSUE TITLE
Which theme do you use

### ISSUE THREAD

**Issue by sistemd** [peitalin/vim-jsx-typescript#34]
What is the name of the theme used in the screenshots, such as https://github.com/peitalin/vim-jsx-typescript/blob/master/screen1.jpg? It's a really nice theme. It might be a good idea to include the theme name as a note somewhere in the readme file for other people who might be wondering.

**Comment by peitalin** [comment]
It's a customized version of "onedark".
Check out these lines in my .vimrc here:
https://github.com/peitalin/dotfiles/blob/53aa7bb022d3c50cf1e9dcba67e7a7a3199b0fe9/.vimrc#L520-L685

You'll need to install the onedark theme:
```vim
" Colorschemes
Plug 'joshdick/onedark.vim'
```

**Comment by sistemd** [comment]
Thank you very much :)
