### ISSUE TITLE
Doesn't handle Fragment short syntax

### ISSUE THREAD

**Issue by DuBistKomisch** [peitalin/vim-jsx-typescript#8]
I'd love to use this plugin but we extensively use `<></>` as an empty element return and it breaks the highlighting for the rest of the file. It's relatively new syntax, see here: https://reactjs.org/docs/fragments.html#short-syntax. Works fine for my coworkers using VS Code of course. :stuck_out_tongue: 

I was going to try fixing this myself but the regexes are pretty confusing. I notice this is kind of a fork of a fork of a fork, perhaps one of them has fixed it already and we can just pull in some updates?

**Comment by peitalin** [comment]
Thanks for bringing this up, I added a syntax rule for fragments. Please let me know if it works.

![image](https://user-images.githubusercontent.com/4037878/51418713-d576f000-1bd0-11e9-946b-f8fecaee2eb4.png)

**Comment by peitalin** [comment]
Thanks for the heads up, I've added some rules for fragments. 
![image](https://user-images.githubusercontent.com/4037878/51420261-75864680-1bdc-11e9-99bf-83b91c3847ca.png)

**Comment by DuBistKomisch** [comment]
@peitalin good timing, was just trying it out, seems like a big improvement but it appears self-closing elements now mess up the typescript highlighting afterwards:

![image](https://user-images.githubusercontent.com/703055/51420295-15e06900-1be5-11e9-9907-9c4b12dc3c75.png)

**Comment by peitalin** [comment]
Ok, let's see if it's working now:
![image](https://user-images.githubusercontent.com/4037878/51423213-2d7d1900-1c08-11e9-88b9-92590e09cb9b.png)

**Comment by DuBistKomisch** [comment]
Seems to be working here as well!
