### ISSUE TITLE
Support for JSX generics

### ISSUE THREAD

**Issue by lucasecdb** [peitalin/vim-jsx-typescript#9]
The support for generics in JSX landed in [TypeScript 2.9](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#generic-type-arguments-in-jsx-elements). I've tried implementing this, but the syntax definition in vim is really confusing. I got it working in a very basic scenario, but if the inner type has any arguments of it's own the angular brackets looks messed up.

This is how it looks without my changes

![image](https://user-images.githubusercontent.com/10223856/53846257-fcc02b80-3f8a-11e9-987b-489158a939ef.png)

And with the changes I've made

![image](https://user-images.githubusercontent.com/10223856/53846302-1c575400-3f8b-11e9-844c-4ccc43ed67f6.png)

As you can see, the second `>` is colored wrong, it should be a plain white color.

**Comment by lucasecdb** [comment]
Also, I forgot this but, the colors after the generics are also wrong, the `initialValues` prop should be colored with a light blue, but I don't know what I messed up

![image](https://user-images.githubusercontent.com/10223856/53846467-c800a400-3f8b-11e9-94af-42a68163c640.png)

**Comment by lucasecdb** [comment]
So far, what I've done is create a `tsxGenerics` region like the following

```viml
syntax region tsxGenerics
    \ start=+<+
    \ end=+>+
    \ contained
    \ contains=Type
```

and add a `nextgroup=tsxGenerics` to the `tsxTagName`

**Comment by peitalin** [comment]
Thanks for letting me know, I've added a few updates to your definition. Let's see if it works on your end.
![image](https://user-images.githubusercontent.com/4037878/53856598-473eb800-401e-11e9-8ca1-a477376419b7.png)

Try adding this in your .vimrc to change the colors to your liking.
```
hi tsxTypeBraces guifg=#BDA7CC
hi tsxTypes guifg=#8D779C
```

**Comment by lucasecdb** [comment]
it worked! thanks @peitalin!
